# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/80a6eafd-7307-4a2d-aabf-a35574cd484a";
      fsType = "ext4";
    };

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/9B96-7746";
      fsType = "vfat";
    };

  fileSystems."/mnt/WinSys" =
   { device = "/dev/disk/by-uuid/1A18F09B18F0775B";
     fsType = "ntfs-3g"; 
     options = [ "rw" "uid=1000" ];
   };

  fileSystems."/mnt/WinData" =
   { device = "/dev/disk/by-uuid/1062EE2062EE09F4";
     fsType = "ntfs-3g"; 
     options = [ "rw" "uid=1000" ];
   };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/dd37ed7e-67a0-4fde-9bdb-9d19c51f1b01"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
